//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Windows.Forms.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class System_Windows_Forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System_Windows_Forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Windows.Forms.resources.System.Windows.Forms", typeof(System_Windows_Forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string _Copy {
            get {
                return ResourceManager.GetString("&Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string _Delete {
            get {
                return ResourceManager.GetString("&Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string _Paste {
            get {
                return ResourceManager.GetString("&Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string _Undo {
            get {
                return ResourceManager.GetString("&Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unknown method&gt;.
        /// </summary>
        internal static string _unknown_method_ {
            get {
                return ResourceManager.GetString("<unknown method>", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string Add_new {
            get {
                return ResourceManager.GetString("Add new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Custom Colors.
        /// </summary>
        internal static string Add_To_Custom_Colors {
            get {
                return ResourceManager.GetString("Add To Custom Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetic.
        /// </summary>
        internal static string Alphabetic {
            get {
                return ResourceManager.GetString("Alphabetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Colors.
        /// </summary>
        internal static string Base_Colors {
            get {
                return ResourceManager.GetString("Base Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bri.
        /// </summary>
        internal static string Bri {
            get {
                return ResourceManager.GetString("Bri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorized.
        /// </summary>
        internal static string Categorized {
            get {
                return ResourceManager.GetString("Categorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string Cu_t {
            get {
                return ResourceManager.GetString("Cu&t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position.
        /// </summary>
        internal static string Current_position {
            get {
                return ResourceManager.GetString("Current position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Custom Colors &gt;&gt;.
        /// </summary>
        internal static string Define_Custom_Colors___ {
            get {
                return ResourceManager.GetString("Define Custom Colors >>", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum argument value &apos;{0}&apos; is not valid for AutoCompleteMode.
        /// </summary>
        internal static string Enum_argument_value___0___is_not_valid_for_AutoCompleteMode {
            get {
                return ResourceManager.GetString("Enum argument value \'{0}\' is not valid for AutoCompleteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum argument value &apos;{0}&apos; is not valid for AutoCompleteSource.
        /// </summary>
        internal static string Enum_argument_value___0___is_not_valid_for_AutoCompleteSource {
            get {
                return ResourceManager.GetString("Enum argument value \'{0}\' is not valid for AutoCompleteSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        internal static string Hue {
            get {
                return ResourceManager.GetString("Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move first.
        /// </summary>
        internal static string Move_first {
            get {
                return ResourceManager.GetString("Move first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move last.
        /// </summary>
        internal static string Move_last {
            get {
                return ResourceManager.GetString("Move last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move next.
        /// </summary>
        internal static string Move_next {
            get {
                return ResourceManager.GetString("Move next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move previous.
        /// </summary>
        internal static string Move_previous {
            get {
                return ResourceManager.GetString("Move previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string of__0_ {
            get {
                return ResourceManager.GetString("of {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string Select__All {
            get {
                return ResourceManager.GetString("Select &All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of items.
        /// </summary>
        internal static string Total_number_of_items {
            get {
                return ResourceManager.GetString("Total number of items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing.
        /// </summary>
        internal static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Colors.
        /// </summary>
        internal static string User_Colors {
            get {
                return ResourceManager.GetString("User Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
